[package]
name = "emscripten-util"
version = "0.1.0"
authors = ["Wieland Hagen <wieland.hagen@kdab.com>"]

[dependencies]
base64 = "0.10.0"
libc = "0.2"
emscripten-sys = "0.3.2"

[build-dependencies]
cc = "1.0"
